remote_theme: nielsenramon/chalk

# Mandatory settings

blog_theme: light # Or use dark
name: evanm
paginate: 25
url: https://notes.evanm.com

# Optional settings

about_enabled: false # Change to true if you wish to show an icon in the navigation that redirects to the about page
rss_enabled: false # Change to false if not
scrollappear_enabled: true # Change to false to disable
tag_nav_enabled: false # Change to true if you wish to show an additional 'tag-list' navigation below the header
theme_toggle: true # Change to true if you wish to show an icon in the navigation for dynamic theme toggling
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  flickr: # Add your Flickr handle
  github: emadow # Add your GitHub handle
  linkedin: # Add your LinkedIn handle
  twitter: emadow # Add your Twitter handle
  email: # Add your Email address
  bitcoin: # Add your Bitcoin link or address
  ethereum: # Add your Ethereum link or address
  gitlab: # Add your GitLab handle
  youtube: # Add your Youtube handle
  twitch: # Add your Twitch handle
  discord: # Add you Discord server invitation ID
  tumblr: # Add your Tumblr handle
  bitbucket: # Add your Bitbucket handle
  docker: # Add your Docker Hub handle
  instagram: # Add your Instagram handle
  keybase: # Add your Keybase handle
  medium: # Add your Medium handle
  spotify: # Add your Spotify handle
  stackoverflow: # Add your Stack Overflow ID number
  steam: # Add your Steam handle
